addons:
  postgresql: '9.4'

before_script:
  - curl --silent -L https://gist.githubusercontent.com/BM5k/38c55d9ffaf6f9865949/raw/database.yml -o config/database.yml
  - bundle exec rake db:setup

bundler_args: --without development production

cache: bundler

env:
  global:
    - SECRET_TOKEN=28e8c098272e0f03d31ae8b52aac6eb4fd14aee5fd299090ef490202b56b4d53f2a133c23c70baf51cd0d81a8a0a9567cb38b5a437389f9edbdc7c1725ba8470

language: ruby

notifications:
  email: false
  slack:
    secure: b7xasQE+FCtZ+ppnVADFpCWtSsIUusPbFceEsj1HtWCpTv6GGd4u5WLk6I7sW1zHn8Xlg8Cg5Si3ba1xyGZUxT2rTQnkV5u4BpKNAelCD0bzaYorXYL3O4etuw3+QAsp7tAfVPAmWnr8GcAW4hIfH2bhVuCGuSoiH3T2caEfbbg=


rvm: 2.2.1
script: RAILS_ENV=test bundle exec rake spec
services: redis-server
sudo: false
